name: Publish Julia Package
author: Shane Cheng
description: Modifies the version number in Julia project.toml (continuously adding new functions)
inputs:
  version:
    description: The version number
    required: false
    default: '0.1.0'
runs:
  using: 'composite'
  steps: 
    - shell: bash
      run: |
        julia run.jl ${{inputs.version}}
        git add Project.toml
        git commit -m "Update version to ${{inputs.version}}"
        git push

branding:
  icon: package
  color: red