name: Publish Julia Package
author: Shane Cheng
description: Modifies the version number in Julia project.toml (continuously adding new functions)
inputs:
  version:
    description: The version number
    required: true
  ssh_key: 
    description: The ssh key for accessing the private Julia registry and the project's git repository
    required: true
  julia_registry_url: 
    description: The private julia registry url
    required: true
  julia_registry_name: 
    description: The private julia registry name
    required: true
runs:
  using: 'composite'
  steps: 
    - shell: bash
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "setting up git credentials"
        mkdir -p /home/runner/.ssh
        echo "${{ inputs.ssh_key }}" > /home/runner/.ssh/id_somekind
        chmod 400 /home/runner/.ssh/id_somekind
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null 
        ssh-add /home/runner/.ssh/id_somekind
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git fetch --all
        git pull
        echo "bumping the Julia package version"
        julia "$GITHUB_ACTION_PATH"/bump_version.jl ${{inputs.version}}
        git add Project.toml
        git commit -m "Update version to ${{inputs.version}}"
        git push
        git tag -a -f ${{inputs.version}} -m "Update version to ${{inputs.version}}"
        git push --tags
        echo "registering Julia package to the registry"
        julia "$GITHUB_ACTION_PATH"/julia_register.jl ${{inputs.julia_registry_name}} ${{inputs.julia_registry_url}}
        cd /home/runner/.julia/registries/${{inputs.julia_registry_name}}/
        git push
branding:
  icon: package
  color: red